version: "3"
services:
  server:
    build:
      context: ./server
    container_name: il-server
    ports:
      - "5000:5000"
    volumes:
      - ./server/src:/app/server/src
      - ./server/package.json:/app/server/package.json
      - ./server/yarn.lock:/app/server/yarn.lock
    depends_on:
      - mongo
  client:
    build:
      context: client
    container_name: il-client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/client/src
      - ./client/package.json:/app/client/package.json
      - ./client/yarn.lock:/app/client/yarn.lock
  mongo:
    image: "mongo:7.0.4"
    container_name: il-mongo
    ports:
      - "27017:27017"
